### ISSUE TITLE
Add Chinese (traditional) in target language

### ISSUE THREAD

**Issue by Regen-forest** [Rapha149/ulauncher-deepl#4]
DeepL has Chinese (traditional) option, but I don't see it in ulauncher-deepl.
![DeepL website shows Chinese (traditional) option](https://github.com/user-attachments/assets/fcb9f3fe-37e1-48ff-9d85-17f2009b13f9)
![There is no Chinese (traditional) option in ulauncher-deepl](https://github.com/user-attachments/assets/7d6380be-9713-417c-b9a1-8fd97f0e8bd9)

**Comment by Rapha149** [comment]
This seems to be an issue with the [DeepL library](https://github.com/DeepLcom/deepl-python) that I use for translating. Please report the issue there.

**Comment by Rapha149** [comment]
However, I did change it so that you can use up to 4 characters in the [quick language selection](https://github.com/Rapha149/ulauncher-deepl?tab=readme-ov-file#quick-language-selection), meaning you can use the language codes to select one of the two chinese languages like this: `tr en:zh apple` or `tr en:zh-hans apple`.
According to deepl.com `zh-hans` is the simplified version while `zh-hant` is the traditional version, but I don't know for sure it's the same in the library and in the library there's only `zh-hans` and `zh`.

**Comment by Regen-forest** [comment]
Thank you!
